### ISSUE TITLE
reoccuring error message

### ISSUE THREAD

**Issue by faithfulman18** [jakepoz/RepDev#16]
This seems to be a regular error message after you have had RepDev opened for a while and doing work within it.  Does anyone know how to prevent this error?

RepDev: 1.6.12

Error Text: Index: 200, Size: 200 - java.lang.IndexOutOfBoundsException
Thu Feb 14 13:53:24 PST 2019

java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
com.repdev.MainShell.addToNavHistory(MainShell.java:2985)
com.repdev.FindReplaceShell.find(FindReplaceShell.java:416)
com.repdev.FindReplaceShell$4.widgetSelected(FindReplaceShell.java:169)
org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
com.repdev.RepDevMain.main(RepDevMain.java:93)
com.repdev.launcher.Launcher.main(Launcher.java:46)

User Notes: 
Enter any notes about the error here. 

(Or a contact email address.)

**Comment by thechillman422** [comment]
Issue has been fixed.

**Comment by faithfulman18** [comment]
Will there be a new release?

**Comment by thechillman422** [comment]
I was not planning on bumping the release just yet.  Are you able to build it yourself? if not, I may have another change coming in a month or so and I can do it then.

**Comment by faithfulman18** [comment]
I'm not sure what is involved in "building" it myself.  ?

**Comment by faithfulman18** [comment]
Is there any instructions on how to create a new build?

**Comment by faithfulman18** [comment]
Is there any instructions on how to create a new build?

**Comment by thechillman422** [comment]
Sorry for the delayed response.  We just went Live with EASE Monday and I am doggone tired.

I do not know of any written instructions to create a new build.  But if you are a future RepDev Code contributor, I'd be happy to walk you through it.  But for now, since I don't have a lot of time, it is easier for me to build a beta version for you.  Go to your RepDev folder and backup the com folder, I do that by renaming the folder from com to com.030619.  Then follow the link below to download the zip file.  Open the Zip file and copy the com Folder to your RepDev Folder.  Launch RepDev and you should be using RepDev 1.6.14 beta.  Sorry, this is all the time I have right now.

https://app.box.com/s/z48nt858k9eegyqpczdbju47qjp8t2dq

**Comment by faithfulman18** [comment]
Thanks.  I appreciate it.
