### ISSUE TITLE
Request: Specify server for each sym

### ISSUE THREAD

**Issue by orayzio** [jakepoz/RepDev#32]
RepDev currently stores a single server in options, but many credit unions have multiple Symitar hosts. I'd like to see an option when creating a new sym to specify the hostname for that sym. I'd also suggest server shortnames that would show up as part of the label for the sym. So, instead of just saying "Sym 000", each sym would show as "Sym 000 Live", "Sym 100 Test", "Sym 100 .5 server", etc.

**Comment by thechillman422** [comment]
We used to have 3 hosts; Symitar, SymDev and SymBu.  We were not allowed to touch SymBu as that is for DR Backup.  Now we only have Symitar and SymitarTest.  Since I log into Test most of the time, I set that as the hostname in options.  When I need to log into Symitar, I just remove "Test" from the host name and log in.  I do like the idea of having a short name tho.  This one may take quite a while.

**Comment by thechillman422** [comment]
This has been completed.  When you log into a SYM, it will remember the Server for that SYM.  I’ve also added the feature to give the SYM a description, i.e. Production, General Test SYM, Month End, etc.  Just right click on the SYM and select SYM Description. These are available in RepDev 1.7.3.
