### ISSUE TITLE
Symitar Update - Problems connecting to Test Environment currently

### ISSUE THREAD

**Issue by lsochia** [jakepoz/RepDev#36]
The newest update Symitar released has caused issues with the connection. I can no longer connect to the test environments. The update is scheduled to be released generally this weekend.

See message below when I try to add our test environment to the ssh cache.

C:\RepDevProg>plink.exe -load aixterm ease
FATAL ERROR: Couldn't agree a key exchange algorithm (available: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256)

**Comment by thechillman422** [comment]
Thank you.  This issue was brought up by SMUG earlier today.  I've posted a link to RepDev 1.7.4 Beta 7 on SMUG for users to test.  If you are on SMUG, please look for my email with the link.  I will follow up with the testing status.

**Comment by lsochia** [comment]
Hello,

Thank you for your reply.  I subscribed to the list, however I don't think
I will get this before Monday morning. Was wondering since I have been
using your IDE almost daily for the last 10+ years and it has become one of
those things that I consider important to my functions, is it possible to
get this beta emailed to me?

My credit union email is: ***@***.***

Thank you,

Lowell Sochia

**Comment by thechillman422** [comment]
Hi Lowell, sorry, just saw this message.  I've noticed that you got onto SMUG and was able to get the link.  Let me know if that is not the case and I can DM you the link.

FYI, this is not "my" IDE.  This was created by Jake Poznanski, the owner of this Repo, along with two of his buddies (Ryan and Sean).  You can see their names in the RepDev credits.  They've since moved on to bigger and better things :)  I just help update RepDev here and there.  I will close this issue (#36) once I push the patch out into the repo.  Thanks again for reporting this bug.

**Comment by lsochia** [comment]
Yes I was able to get the link for download. Thank you.

How can I help out getting the issue resolved? I have noticed that the Beta
is still not connecting. I have tried this on 2 different PC's just to make
sure. Is there any log files I can provide to you or should I start a new
thread with the users group? I don't mind helping out troubleshooting.


Lowell Sochia

**Comment by thechillman422** [comment]
I DM'd you.

**Comment by thechillman422** [comment]
Since beta7 worked for you, I've pushed out the patch and will close this issue now.  Thanks.

**Comment by lsochia** [comment]
That's good to hear. Thank you for the fix, it is very much appreciated.
