### ISSUE TITLE
AIX Password is Due to Expire

### ISSUE THREAD

**Issue by jc6036** [jakepoz/RepDev#39]
This is less of a direct issue report and more of a question.

The return message "Your password will expire:" triggers a failure to connect to a sym. Is this necessary? As in, will AIX refuse the connection unless the password is updated? Or is this a design choice on the repdev side of things? We are having some access issues with the way our system is configured resulting in some really PITA moments where we can't get our password reset for some time and we effectively can't use repdev right. 

Not suggesting a change to make up for the way our stuff is set up, but wondering if its necessary. If not I may fork and remove the disconnect logic so we can still use repdev in these cases.

**Comment by thechillman422** [comment]
Hi Jesse,

I have tried many times to "ignore" the password will expire message, but it always puts me into Symulate mode (not sure if you're old enough to know what that means :D ).  And then RepDev would freeze.  I've had times when I had unsaved work in RepDev and I tried to log int another SYM, when my password was due to expire, and caused RepDev to freeze and lost my work.  I figure it would have been better to just pop up a message and users can continue in RepDev without loosing their work.

We are hosted by EASE, not sure if that has anything to do with it, but you can definitely fork and remove the disconnect logic to see if it works for you.

If it helps, you can create a file called FullTrace.XXX.txt in the RepDev folder.  XXX=the SYM number that you are logging into.  This may give you a glimpse of what is going back and forth between RepDev and Symitar.  The information sent by RepDev will be between > and <.  Make sure to delete or remove that file once you're done so that it does not slow down your sessions.

Let me know how it works out for you.  Bruce

**Comment by jc6036** [comment]
We are on EASE as well so guessing it would be the same issue there. Thanks, answered exactly what I was wondering about! I may follow up with the trace log if the team decides to pursue it further. Appreciate the response.
